### ISSUE TITLE
Is it OK to have different dictionaries for different buffers?

### ISSUE THREAD

**Issue by xlwang233** [mie-lab/location-prediction#3]
Hi Ye Hong,

Thank you for your great work. I have a  question that I hope you can enlighten me about. 

In the context vectors calculation in poi.py, you specify 11 buffer distances and calculate the land use context under each distance. This results in different dictionaries for each buffer. Do you think it is okay that the context vectors are derived with different dictionaries?

My initial thought is that it is not right, and we should use one dictionary to calculate all the context vectors. However, when it comes to how you actually use the context vectors, it seems that it doesn't really matter, since the aggregation of the context vectors is done through a neural network (POINet). The different context vectors represent the different topic (poi category) distribution and the topics/categories don't have to be the same (or in the same order), especially under the non-linear aggregation of neural networks. Ultimately, the model performance is not affected - I am not so sure about it, so please correct me if I am wrong.

That being said, I think it is still beneficial to only have one dictionary as it is more rigorous and easier to be interpreted. 

What do you think of this issue? I would appreciate it if you could share your thoughts. Thanks.

**Comment by hongyeehh** [comment]
Hi xlwang233,

Thanks for your interest in our work. I am not sure if I understand what you refer to with `dictionary`: 
- if this refers to the `gensim.corpora.Dictionary` object, we need to create separate dictionaries as the buffer distance changes will affect what POIs are considered near a location. 
- if this refers to the dictionary that stores the various lda vector, i.e., `poi_dict`: this is just a choice, and you can use e.g. a list or a single dictionary. The order of the respective lda vectors does not matter as we use a NN afterward.

**Comment by xlwang233** [comment]
Hi Ye Hong,

Thank you very much for your response. Your explanation cleared my concerns. :)
