### ISSUE TITLE
Dataset split into test, train, validation

### ISSUE THREAD

**Issue by adonnini** [mie-lab/location-prediction#6]
Hi,

The paper

"Context-aware multi-head self-attentional neural network model for next location prediction" 

mentions that

```We split the GNSS tracking datasets into non-overlapping train, validation, and test sets with the ratio of 6:2:2 based on time, such that stay point sequences occurred in the first 60% of tracking days for each user are regarded as train and the last 20% of days as test. 
```
Do the lines
```
    train_split = maxDay * 0.6
    validation_split = maxDay * 0.8
```
in
https://github.com/mie-lab/location-prediction/blob/3417149da1e1e47ac9c5dfe5b557b19e33e96c96/preprocessing/utils.py#L213

match the 6:2:2 ratio? I am confused by the value of 
```validation_split```

Thanks

**Comment by hongyeehh** [comment]
Hi,

Yes, the codes do match the 6:2:2 ratio, see lines
https://github.com/mie-lab/location-prediction/blob/3417149da1e1e47ac9c5dfe5b557b19e33e96c96/preprocessing/utils.py#L219C3-L221

**Comment by adonnini** [comment]
Hi, Thanks. I did see those lines. However, I am not sure it is as you say.

with 
```    
    train_split = maxDay * 0.6
    validation_split = maxDay * 0.8
```
as in
https://github.com/mie-lab/location-prediction/blob/3417149da1e1e47ac9c5dfe5b557b19e33e96c96/preprocessing/utils.py#L216C1-L218C1

when I print ```maxDay```, ```train_split```, and ```validation_split```

I get

```
LocationPrediction - utils.py - _get_split_days_user - maxDay -  4
LocationPrediction - utils.py - _get_split_days_user - train_split -  2.4
LocationPrediction - utils.py - _get_split_days_user - validation_split -  3.2
```
which I don't think correponds to the 6:2:2 ratio

What am I not understanding?

Thanks

**Comment by hongyeehh** [comment]
I am not sure about your question - according to your numbers, the sets are constructed as follows:

train: day 0 - 2.4
vali: day 2.4 - 3.2
test: day 3.2 - 4 

Which matches 6:2:2. With a larger `maxDay` (longer tracking duration), we will match the split more accurately.

**Comment by adonnini** [comment]
Thank you for the clarification. I am all set. Thanks
